x-service-prod: &service-prod
  build:
    target: prod
  volumes: []  # Shared volumes (if any) can be defined here


services:
  web-api:
    <<: *service-prod
    # image: ghcr.io/specterops/nemesis-2.0/web-api:latest

  noseyparker-scanner:
    <<: *service-prod
    # image: ghcr.io/specterops/nemesis-2.0/noseyparker-scanner:latest

  dotnet-api:
    <<: *service-prod
    # image: ghcr.io/specterops/nemesis-2.0/dotnet-api:latest

  file-enrichment:
    <<: *service-prod
    # image: ghcr.io/specterops/nemesis-2.0/file-enrichment:latest
    volumes: []
    #  Depending on RAM available, this may kill the UVICORN process, so disabling by default
    #  - ./libs/file_enrichment_modules/yara_rules/prod:/yara_rules/:ro
    environment:
      - LOG_LEVEL=INFO
      - UVICORN_WORKERS=2

  frontend:
    <<: *service-prod
    # image: ghcr.io/specterops/nemesis-2.0/frontend:latest
    command: >
      sh -c "
        SECRET=\"$$HASURA_ADMIN_SECRET\" &&
        sed -i \"s/\\$$HASURA_ADMIN_SECRET/$$SECRET/g\" /usr/share/nginx/html/index.html &&
        nginx -g 'daemon off;'
      "

  alerting:
    <<: *service-prod
    # image: ghcr.io/specterops/nemesis-2.0/alerting:latest

  jupyter:
    # <<: *service-prod
    # image: ghcr.io/specterops/nemesis-2.0/jupyter:latest

  housekeeping:
    <<: *service-prod
    # image: ghcr.io/specterops/nemesis-2.0/housekeeping:latest

  triage:
    <<: *service-prod
    # image: ghcr.io/specterops/nemesis-2.0/triage:latest

  document-conversion:
    <<: *service-prod
    # image: ghcr.io/specterops/nemesis-2.0/document-conversion:latest
