apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: schedulerconfig
spec:
  tracing:
    expandParams: true
    samplingRate: "1"
    otel:
      protocol: grpc
      endpointAddress: "otel-collector:4317"
      isSecure: false
  features:
    - name: SchedulerReminders
      enabled: true
    - name: pubsub.routing
      enabled: true
  metric:
    enabled: true
  httpPipeline:
    handlers:
    - name: maximum-request-size
      type: middleware.http.requestsize
      properties:
        maxBodySize: "300MB"

  # policies: # TODO: determine how to use these
  #   # Global Retry Policy
  #   DefaultRetryPolicy:
  #     policy: constant
  #     duration: 1s
  #     maxRetries: 3
  #   # Global Retry Policy for Apps
  #   DefaultAppRetryPolicy:
  #     policy: constant
  #     duration: 100ms
  #     maxRetries: 5
  #   # Global Retry Policy for Apps
  #   DefaultActorRetryPolicy:
  #     policy: exponential
  #     maxInterval: 15s
  #     maxRetries: 10
  #   # Global Retry Policy for Inbound Component operations
  #   DefaultComponentInboundRetryPolicy:
  #     policy: constant
  #     duration: 5s
  #     maxRetries: 5
