name: Build and Publish Service Docker Images

on:
  push:
    # # To run on every push to main
    # branches: [ "main" ]

    # To run when release tags are created:
    tags: [ "v*.*.*" ]
  workflow_dispatch: # For manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: "specterops/nemesis" # ${{ github.repository }} causes issues as SpecterOps is not all lowercase

jobs:

  build-service-images:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - runner: ubuntu-22.04
            platform: linux/amd64
            arch: amd64
          - runner: ubuntu-22.04-arm
            platform: linux/arm64
            arch: arm64
        service:
          - name: web-api
            context: .
            dockerfile: ./projects/web_api/Dockerfile
          - name: dotnet-api
            context: .
            dockerfile: ./projects/dotnet_api/Dockerfile
          - name: file-enrichment
            context: .
            dockerfile: ./projects/file_enrichment/Dockerfile
          - name: frontend
            context: ./projects/frontend
            dockerfile: ./projects/frontend/Dockerfile
          - name: jupyter
            context: ./projects/jupyter
            dockerfile: ./projects/jupyter/Dockerfile
          - name: alerting
            context: .
            dockerfile: ./projects/alerting/Dockerfile
          - name: triage
            context: .
            dockerfile: ./projects/triage/Dockerfile
          - name: cli
            context: .
            dockerfile: ./projects/cli/Dockerfile
          - name: housekeeping
            context: .
            dockerfile: ./projects/housekeeping/Dockerfile
          - name: document-conversion
            context: .
            dockerfile: ./projects/document_conversion/Dockerfile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for ${{ matrix.service.name }} image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service.name }}
          tags: |
            type=sha,format=short,suffix=-${{ matrix.arch }}
            type=ref,event=branch,suffix=-${{ matrix.arch }}
            type=ref,event=tag,suffix=-${{ matrix.arch }}
            type=raw,value=${{ github.ref_name }}-${{ matrix.arch }},enable=${{ github.event_name == 'workflow_dispatch' }}
            type=raw,value=latest-${{ matrix.arch }},enable={{is_default_branch}}

      - name: Build and push ${{ matrix.service.name }} image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PYTHON_BASE_DEV_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/python-base-dev:latest
            PYTHON_BASE_PROD_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/python-base-prod:latest
            INSPECT_ASSEMBLY_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/inspect-assembly:latest
          cache-from: type=gha,scope=${{ matrix.service.name }}-${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service.name }}-${{ matrix.arch }}

            # # If wanting to use the proper tag
            # PYTHON_BASE_DEV_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/python-base-dev:${{ needs.build-base-images.outputs.python-base-dev-tag }}
            # PYTHON_BASE_PROD_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/python-base-prod:${{ needs.build-base-images.outputs.python-base-prod-tag }}

  # Create multi-arch manifests
  create-manifests:
    needs: build-service-images
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service:
          - web-api
          - dotnet-api
          - file-enrichment
          - frontend
          - jupyter
          - alerting
          - triage
          - cli
          - housekeeping
          - document-conversion

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for ${{ matrix.service }} manifest
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=${{ github.ref_name }},enable=${{ github.event_name == 'workflow_dispatch' }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Create and push ${{ matrix.service }} multi-arch manifest
        run: |
          # Get the base image name
          BASE_IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}"

          echo '${{ steps.meta.outputs.tags }}' | while IFS= read -r tag; do
            if [ -n "$tag" ]; then
              echo "Creating manifest for: $tag"
              # Determine the tag suffix (e.g., "main", "sha-abc123", "latest", "manual")
              TAG_SUFFIX=$(echo "$tag" | sed "s|${BASE_IMAGE}:||")

              docker buildx imagetools create \
                --tag "$tag" \
                "${BASE_IMAGE}:${TAG_SUFFIX}-amd64" \
                "${BASE_IMAGE}:${TAG_SUFFIX}-arm64"
            fi
          done