name: Build and Publish the noseyparker-scanner Docker Image

on:
  workflow_dispatch: # For manual triggering
  # push:
  #   branches: [ "main" ]
  #   # Trigger on changes to noseyparker-scanner files
  #   paths:
  #     - 'projects/noseyparker_scanner/**'
  #     - '.github/workflows/noseyparker-scanner-build.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: "specterops/nemesis"
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-noseyparker-scanner:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service:
          - name: noseyparker-scanner
            context: .
            dockerfile: ./projects/noseyparker_scanner/Dockerfile.new
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Use larger instance for better performance
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      # Pre-warm Rust registry cache
      - name: Cache Rust registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for ${{ matrix.service.name }} image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service.name }}
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=cache

      - name: Build and push ${{ matrix.service.name }} image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            CARGO_INCREMENTAL=0
            CARGO_TERM_COLOR=always
            RUST_BACKTRACE=1
            CARGO_BUILD_JOBS=4
          # Enhanced multi-layer caching with registry
          cache-from: |
            type=gha,scope=noseyparker-scanner-${{ github.ref_name }}
            type=gha,scope=noseyparker-scanner-main
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/noseyparker-scanner:cache
          cache-to: |
            type=gha,mode=max,scope=noseyparker-scanner-${{ github.ref_name }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/noseyparker-scanner:cache,mode=max

      - name: Test built image
        run: |
          # Test that the image runs and shows version
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/noseyparker-scanner:${{ steps.meta.outputs.version }} --help || true

      # Clean up cache on successful build to prevent cache bloat
      - name: Cleanup old cache entries
        if: success()
        run: |
          # Clean up old GitHub Actions cache entries for this scope
          gh extension install actions/gh-actions-cache || true
          gh actions-cache delete "noseyparker-scanner-${{ github.ref_name }}-*" --confirm || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true